# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-12.6"
    debian.vm.box_version = "202407.22.0"
    debian.vm.hostname = "debian-vm"
    debian.vm.network "private_network", ip: "192.168.56.10"
    
    debian.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "ubuntu-vm"
    ubuntu.vm.network "private_network", ip: "192.168.56.11"
    
    ubuntu.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end
end