version: '3.8'

services:
  traefik:
    image: 192.168.56.101:5000/traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

  apache:
    image: 192.168.56.101:5000/httpd:latest
    container_name: apache
    networks:
      - traefik-public
      - my_network
    depends_on:
      - traefik
      - django
    configs:
      - source: proxy_conf
        target: /usr/local/apache2/conf/extra/default.conf
        mode: 0440
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apache.rule=Host(`example.com`)"
        - "traefik.http.services.apache.loadbalancer.server.port=80"
        - "traefik.http.routers.apache.entrypoints=web,websecure"
  
  django:
    image: 192.168.56.101:5000/django-custom:latest
    container_name: django
    networks:
      - traefik-public
      - my_network
    depends_on:
        - db
        - apache
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
        - DATABASE_HOST=db
        - DATABASE_NAME=mydatabase
        - DATABASE_USER=admin
        - DATABASE_PASSWORD=/run/secrets/mysql_password
    secrets:
        - mysql_password
    configs:
        - source: django_config
          target: /app/modele/settings.py
          mode: 0440
    volumes:
      - app:/app

  db:
    image: 192.168.56.101:5000/mysql:latest
    container_name: db
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=mydatabase
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - mysql_password
      - mysql_root_password

      
secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true

networks:
  traefik-public:
    external: true
  my_network:

volumes:
  db: