FROM python:3.12-alpine

RUN apk add --no-cache mariadb-dev build-base

COPY ./app /app

WORKDIR /app

RUN pip install --no-cache-dir django==5.1.2 mysqlclient==2.2.4 gunicorn==23.0.0

CMD ["gunicorn", "modele.wsgi:application", "--bind", "0.0.0.0:8000"]